/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DemoTableImport } from './routes/demo.table'
import { Route as DemoDaisyUiImport } from './routes/demo.daisy-ui'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTableRoute = DemoTableImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRoute,
} as any)

const DemoDaisyUiRoute = DemoDaisyUiImport.update({
  id: '/demo/daisy-ui',
  path: '/demo/daisy-ui',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/demo/daisy-ui': {
      id: '/demo/daisy-ui'
      path: '/demo/daisy-ui'
      fullPath: '/demo/daisy-ui'
      preLoaderRoute: typeof DemoDaisyUiImport
      parentRoute: typeof rootRoute
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/daisy-ui': typeof DemoDaisyUiRoute
  '/demo/table': typeof DemoTableRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/daisy-ui': typeof DemoDaisyUiRoute
  '/demo/table': typeof DemoTableRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/demo/daisy-ui': typeof DemoDaisyUiRoute
  '/demo/table': typeof DemoTableRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/daisy-ui' | '/demo/table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/daisy-ui' | '/demo/table'
  id: '__root__' | '/' | '/demo/daisy-ui' | '/demo/table'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoDaisyUiRoute: typeof DemoDaisyUiRoute
  DemoTableRoute: typeof DemoTableRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoDaisyUiRoute: DemoDaisyUiRoute,
  DemoTableRoute: DemoTableRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demo/daisy-ui",
        "/demo/table"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/demo/daisy-ui": {
      "filePath": "demo.daisy-ui.tsx"
    },
    "/demo/table": {
      "filePath": "demo.table.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
